CompanyProject/Controllers/KaryawanController.cs
using CompanyProject.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CompanyProject.Controllers
{
    public class KaryawanController : Controller
    {
        // GET: Karyawan
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoadData(JqueryDataTableParam param)
        {
            try
            {
                
                using (DatabaseContext _context = new DatabaseContext())
                {
                    // Getting all data karyawan
                    var dataKaryawan = (from temp in _context.Karyawan
                                        select new
                                        {
                                            temp.Id,
                                            temp.Nama,
                                            temp.TanggalLahir,
                                            temp.JumlahAnak,                                            
                                            TanggalLahirString = SqlFunctions.DateName("day", temp.TanggalLahir) + " " + SqlFunctions.DateName("month", temp.TanggalLahir) + " " + SqlFunctions.DateName("year", temp.TanggalLahir),
                                            Umur = DateTime.Now.Year - temp.TanggalLahir.Year
                                        });



                    //Search    
                    if (!string.IsNullOrEmpty(param.sSearch))
                    {
                        dataKaryawan = dataKaryawan.Where(m => m.Nama.ToLower().Contains(param.sSearch.ToLower())
                                                    || m.TanggalLahirString.ToString().ToLower().Contains(param.sSearch.ToLower())
                                                    || m.JumlahAnak.ToString().Contains(param.sSearch)
                                                    || m.Umur.ToString().Contains(param.sSearch)
                        );
                    }

                    dataKaryawan = dataKaryawan.OrderBy(c => c.Id);                    
                    var displayResult = dataKaryawan.Skip(param.iDisplayStart).Take(param.iDisplayLength).ToList();
                    
                    var totalRecords = dataKaryawan.Count();
                    
                    
                    return Json(new
                    {
                        param.sEcho,
                        iTotalRecords = totalRecords,
                        iTotalDisplayRecords = totalRecords,
                        aaData = displayResult
                    }, JsonRequestBehavior.AllowGet);

                }
            }
            catch (Exception)
            {
                throw;
            }

        }
    
    }
}

CompanyProject/Controllers/KendaraanPerusahaanController.cs
using CompanyProject.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CompanyProject.Controllers
{
    public class KendaraanPerusahaanController : Controller
    {
        // GET: KendaraanPerusahaan
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoadData(JqueryDataTableParam param)
        {
            try
            {

                using (DatabaseContext _context = new DatabaseContext())
                {
                    // Getting all data kendaraab
                    var dataKendaraan = (from temp in _context.KendaraanPerusahaan
                                        select new
                                        {
                                            temp.Id,
                                            temp.Tipe,
                                            temp.Warna,
                                            temp.JumlahRoda,
                                            TanggalBeliString = SqlFunctions.DateName("day", temp.TanggalBeli) + " " + SqlFunctions.DateName("month", temp.TanggalBeli) + " " + SqlFunctions.DateName("year", temp.TanggalBeli)                                           
                                        });



                    //Search    
                    if (!string.IsNullOrEmpty(param.sSearch))
                    {
                        dataKendaraan = dataKendaraan.Where(m => m.Tipe.ToLower().Contains(param.sSearch.ToLower())
                                                    || m.Warna.ToLower().Contains(param.sSearch.ToLower())
                                                    || m.TanggalBeliString.ToString().ToLower().Contains(param.sSearch.ToLower())
                                                    || m.JumlahRoda.ToString().Contains(param.sSearch)
                                                    
                        );
                    }

                    dataKendaraan = dataKendaraan.OrderBy(c => c.Id);
                    var displayResult = dataKendaraan.Skip(param.iDisplayStart).Take(param.iDisplayLength).ToList();

                    var totalRecords = dataKendaraan.Count();


                    return Json(new
                    {
                        param.sEcho,
                        iTotalRecords = totalRecords,
                        iTotalDisplayRecords = totalRecords,
                        aaData = displayResult
                    }, JsonRequestBehavior.AllowGet);

                }
            }
            catch (Exception)
            {
                throw;
            }

        }

        public ActionResult GetDataTipe()
        {
            try
            {

                using (DatabaseContext _context = new DatabaseContext())
                {
                    // Getting all data kendaraab
                    var dataTipe = (from temp in _context.KendaraanPerusahaan
                                    select new
                                    {
                                        temp.Tipe
                                    }).ToList().Distinct();
                                         



                    return Json(dataTipe);

                }
            }
            catch (Exception)
            {
                throw;
            }

        }
    }
}

CompanyProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sistem Informasi Kendaraan </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    
    <link href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" rel="stylesheet" />
</head>
<body>
    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar">
            <div class="p-4 pt-5">
                <ul class="list-unstyled components mb-5">
                    <li>@Html.ActionLink("Data Karyawan", "Index", "Karyawan")</li>
                    <li>@Html.ActionLink("Data Kendaraan Perusahaan", "Index", "KendaraanPerusahaan")</li>
                </ul>
            </div>
        </nav>

        <div id="content" class="p-4 p-md-5 pt-5">           
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/datetime/1.1.2/js/dataTables.dateTime.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>